<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27234" started-at="2020-10-28T08:08:53 IST" finished-at="2020-10-28T08:09:20 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27234" started-at="2020-10-28T08:08:53 IST" finished-at="2020-10-28T08:09:20 IST">
      <class name="testCase.Common">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testCase.Common@59e5ddf]" name="setUp" is-config="true" duration-ms="5240" started-at="2020-10-28T08:08:53 IST" finished-at="2020-10-28T08:08:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="allCases()[pri:1, instance:testCase.Common@59e5ddf]" name="allCases" duration-ms="13280" started-at="2020-10-28T08:08:58 IST" finished-at="2020-10-28T08:09:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allCases -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testCase.Common@59e5ddf]" name="tearDown" is-config="true" duration-ms="647" started-at="2020-10-28T08:09:11 IST" finished-at="2020-10-28T08:09:12 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=allCases status=SUCCESS method=Common.allCases()[pri:1, instance:testCase.Common@59e5ddf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="allCases2()[pri:2, instance:testCase.Common@59e5ddf]" name="allCases2" duration-ms="7115" started-at="2020-10-28T08:09:12 IST" finished-at="2020-10-28T08:09:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Computers] but found [Apparel]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Computers] but found [Apparel]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at pageObject.CategoriesPage.match_FirstName(CategoriesPage.java:105)
at testCase.Common.allCases2(Common.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allCases2 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testCase.Common@59e5ddf]" name="tearDown" is-config="true" duration-ms="909" started-at="2020-10-28T08:09:19 IST" finished-at="2020-10-28T08:09:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=allCases2 status=FAILURE method=Common.allCases2()[pri:2, instance:testCase.Common@59e5ddf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDownSuite()[pri:0, instance:testCase.Common@59e5ddf]" name="tearDownSuite" is-config="true" duration-ms="1121" started-at="2020-10-28T08:09:20 IST" finished-at="2020-10-28T08:09:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- testCase.Common -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
